const VOCABULARY = [
    { id: 'apple', word: 'Apple', icon: 'apple', color: '#ef4444' },
    { id: 'car', word: 'Car', icon: 'car', color: '#3b82f6' },
    { id: 'dog', word: 'Dog', icon: 'dog', color: '#b45309' },
    { id: 'cat', word: 'Cat', icon: 'cat', color: '#fb923c' },
    { id: 'sun', word: 'Sun', icon: 'sun', color: '#facc15' },
    { id: 'moon', word: 'Moon', icon: 'moon', color: '#94a3b8' },
    { id: 'star', word: 'Star', icon: 'star', color: '#eab308' },
    { id: 'cloud', word: 'Cloud', icon: 'cloud', color: '#93c5fd' },
    { id: 'fish', word: 'Fish', icon: 'fish', color: '#06b6d4' },
    { id: 'bird', word: 'Bird', icon: 'bird', color: '#0ea5e9' },
    { id: 'house', word: 'House', icon: 'house', color: '#059669' },
    { id: 'bed', word: 'Bed', icon: 'bed', color: '#818cf8' },
    { id: 'book', word: 'Book', icon: 'book', color: '#f43f5e' },
    { id: 'phone', word: 'Phone', icon: 'phone', color: '#a855f7' },
    { id: 'plane', word: 'Plane', icon: 'plane', color: '#2563eb' },
    { id: 'boat', word: 'Boat', icon: 'ship', color: '#14b8a6' },
    { id: 'hammer', word: 'Hammer', icon: 'hammer', color: '#6b7280' },
    { id: 'flower', word: 'Flower', icon: 'flower-2', color: '#ec4899' },
    { id: 'tree', word: 'Tree', icon: 'tree-deciduous', color: '#16a34a' },
    { id: 'ghost', word: 'Ghost', icon: 'ghost', color: '#a5b4fc' },
];
